<a href="https://colab.research.google.com/github/SAIF2584/classification_algorithms/blob/main/Spam_email_ditectionUsingNaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np
import seaborn as sns

In [36]:
df = pd.read_csv('/content/emails.csv')

In [37]:
df['spam'].value_counts()

spam
0                                                                                               4359
1                                                                                               1367
 its termination would not  have such a phenomenal impact on the power situation .  however        1
 mr suresh prabhu                                                                                  1
Name: count, dtype: int64

In [38]:
df.drop_duplicates(inplace=True)

In [39]:
df.isnull().sum()

text               0
spam               2
Unnamed: 2      5695
Unnamed: 3      5695
Unnamed: 4      5695
                ...
Unnamed: 105    5695
Unnamed: 106    5695
Unnamed: 107    5696
Unnamed: 108    5696
Unnamed: 109    5696
Length: 110, dtype: int64

In [50]:
df.dropna(subset=['spam'], inplace=True)
df = df[df['spam'].isin(['0', '1'])].copy() # Explicitly create a copy
df['spam'] = df['spam'].astype(int)
x = df.text.values
y = df.spam.values

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

In [44]:
cv = CountVectorizer()

In [45]:
x_train = cv.fit_transform(xtrain)

In [46]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [47]:
from sklearn.naive_bayes import MultinomialNB

In [48]:
model = MultinomialNB()

In [49]:
model.fit(x_train, ytrain)

MultinomialNB()

In [51]:
x_test = cv.transform(xtest)

In [52]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [53]:
model.score(x_test, ytest)

0.9938542581211589

In [59]:
email = ["Hi Sarah, just following up on the quarterly report—could you let me know if you need any more data from my end before the meeting tomorrow?","Hey! Are we still on for pizza at 7:00 PM tonight? Let me know if I should grab a table or if you're running late.","Your dental cleaning is confirmed for Tuesday, October 14th at 10:00 AM. Please arrive 5 minutes early to update your paperwork.","URGENT: You are the sole beneficiary of a $5,000,000 estate from a distant relative; please reply with your bank details to initiate the transfer.","Your account has been compromised! Click this link immediately to verify your identity or your profile will be permanently deleted in 2 hours.","CONGRATULATIONS! Your email address was selected as the lucky winner of a brand new iPhone 15 Pro. Just pay $1.99 for shipping to claim it now!","LOSE 20 LBS IN 3 DAYS! Try this one weird trick that doctors hate. Limited time offer, buy now for 90% off!","Please find your attached invoice #88291 for your recent $1,200 purchase."]

In [60]:
cv_email = cv.transform(email)

In [61]:
model.predict(cv_email)

array([0, 0, 0, 1, 1, 1, 1, 0])